### ISSUE TITLE
Popping up a ZAlertView menu will change app status bar to black

### ISSUE THREAD

**Issue by idokleinman** [zelic91/ZAlertView#14]
I have a light content status bar app - when I pop up a multiple choice ZAlertView app status bar momentarily changes to black. Any workaround for that?

**Comment by zelic91** [comment]
Please checkout the version 0.2.1. By default, the dialog will use the status bar style in Info.plist. You can also set the value manually with ZAlertView.

**Comment by Gerst20051** [comment]
I created this class in order to hide the status bar as my app has it hidden.

```
import ZAlertView

class Dialog: ZAlertView {

    init(type: AlertType) {
        super.init(title: nil, message: nil, alertType: type)
    }

    required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

    override var prefersStatusBarHidden: Bool {
        return true
    }

}
```
