### ISSUE TITLE
cocoa pods update issue

### ISSUE THREAD

**Issue by Dileepyadav** [zelic91/ZAlertView#20]
I didn't get updated source code(swift 3.0) when i updating my cocoa pods
Please resolve the issue

**Comment by otymartin** [comment]
@Dileepyadav  i had to do this in my pod file
  ``pod 'ZAlertView', :git => 'https://github.com/zelic91/ZAlertView.git', :branch => 'master'`

**Comment by zelic91** [comment]
Thanks for reporting the issue, I've just rebuilt and uploaded version 0.3.2 which supports Swift 3.
